@echo off
REM build.bat  —  TallySyncManager full build pipeline
REM ====================================================
REM  Step 1  Install PyInstaller
REM  Step 2  Write hooks\hook-cryptography.py
REM  Step 3  Clean old build artifacts
REM  Step 4  Build EXE folder via PyInstaller
REM  Step 5  Copy .env to dist folder
REM  Step 6  Compile Inno Setup installer  <-- NEW
REM
REM Run this from your project root (where main.py lives).
REM Double-click it or run it in your terminal.

echo.
echo ============================================
echo   TallySyncManager - Full Build Pipeline
echo ============================================
echo.

REM ── Configurable paths ──────────────────────────────────────────────────────
REM If Inno Setup is installed somewhere else, update this path.
REM IMPORTANT: use  set "VAR=value"  syntax (quotes wrap the whole assignment,
REM NOT just the value). This stops cmd.exe treating (x86) as a code block.
set "INNO_COMPILER=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 1: Install PyInstaller
REM ─────────────────────────────────────────────────────────────────────────────
echo [1/6] Installing PyInstaller...
uv add pyinstaller --dev
if %errorlevel% neq 0 (
    echo ERROR: Failed to install PyInstaller
    pause
    exit /b 1
)

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 2: Write hooks\hook-cryptography.py
REM ─────────────────────────────────────────────────────────────────────────────
echo.
echo [2/6] Writing hooks\hook-cryptography.py (AppLocker workaround)...

if not exist hooks mkdir hooks

(
echo # hooks/hook-cryptography.py  -- AUTO-GENERATED by build.bat
echo import glob, os
echo from PyInstaller.utils.hooks import collect_data_files
echo.
echo datas = collect_data_files^('cryptography'^)
echo.
echo def _find_binaries^(^)^:
echo     try^:
echo         import importlib.util
echo         spec = importlib.util.find_spec^('cryptography'^)
echo         if spec is None or not spec.submodule_search_locations^:
echo             return []
echo         pkg_dir = list^(spec.submodule_search_locations^)[0]
echo     except Exception^:
echo         return []
echo     result = []
echo     for pattern in ^('*.pyd', '*.dll', '*.so'^)^:
echo         for src in glob.glob^(os.path.join^(pkg_dir, '**', pattern^), recursive=True^)^:
echo             parent = os.path.dirname^(pkg_dir^)
echo             dest   = os.path.relpath^(os.path.dirname^(src^), parent^)
echo             result.append^(^(src, dest^)^)
echo     return result
echo.
echo binaries = _find_binaries^(^)
echo.
echo hiddenimports = [
echo     'cryptography',
echo     'cryptography.fernet',
echo     'cryptography.hazmat',
echo     'cryptography.hazmat.primitives',
echo     'cryptography.hazmat.primitives.ciphers',
echo     'cryptography.hazmat.primitives.ciphers.algorithms',
echo     'cryptography.hazmat.primitives.ciphers.modes',
echo     'cryptography.hazmat.primitives.hashes',
echo     'cryptography.hazmat.primitives.hmac',
echo     'cryptography.hazmat.primitives.padding',
echo     'cryptography.hazmat.primitives.serialization',
echo     'cryptography.hazmat.primitives.asymmetric',
echo     'cryptography.hazmat.primitives.asymmetric.rsa',
echo     'cryptography.hazmat.backends',
echo     'cryptography.hazmat.backends.openssl',
echo     'cryptography.hazmat.bindings._rust',
echo     'cryptography.hazmat.bindings._rust.openssl',
echo     'cryptography.x509',
echo ]
) > hooks\hook-cryptography.py

if %errorlevel% neq 0 (
    echo ERROR: Failed to write hooks\hook-cryptography.py
    pause
    exit /b 1
)
echo    hooks\hook-cryptography.py written OK

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 3: Clean previous build artifacts
REM ─────────────────────────────────────────────────────────────────────────────
echo.
echo [3/6] Cleaning old build files...
if exist build rmdir /s /q build
if exist dist  rmdir /s /q dist
if exist installer_output rmdir /s /q installer_output

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 4: Build the EXE folder via PyInstaller
REM ─────────────────────────────────────────────────────────────────────────────
echo.
echo [4/6] Building EXE folder - this takes 2-5 minutes...
uv run pyinstaller tally_app.spec

if %errorlevel% neq 0 (
    echo.
    echo ERROR: PyInstaller build failed. Check the output above for errors.
    pause
    exit /b 1
)

echo.
echo    PyInstaller build complete: dist\TallySyncManager\TallySyncManager.exe

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 5: Copy .env to dist folder
REM ─────────────────────────────────────────────────────────────────────────────
echo.
echo [5/6] Copying .env to dist\TallySyncManager\...
if exist .env (
    copy /y .env dist\TallySyncManager\.env > nul
    echo    .env copied OK
) else (
    echo    WARNING: .env not found - update password will not work at runtime.
    echo    Create a .env file with:  update_pass=yourpassword
)

REM ─────────────────────────────────────────────────────────────────────────────
REM Step 6: Compile Inno Setup installer
REM ─────────────────────────────────────────────────────────────────────────────
echo.
echo [6/6] Compiling installer with Inno Setup...

if not exist "%INNO_COMPILER%" (
    echo.
    echo ============================================================
    echo   WARNING: Inno Setup not found at:
    echo   %INNO_COMPILER%
    echo.
    echo   Download and install it (free) from:
    echo   https://jrsoftware.org/isinfo.php
    echo.
    echo   Then re-run this build.bat, or open installer.iss
    echo   manually in the Inno Setup Compiler and press F9.
    echo ============================================================
    echo.
    echo   PyInstaller EXE is ready at:
    echo   dist\TallySyncManager\TallySyncManager.exe
    echo.
    pause
    exit /b 0
)

"%INNO_COMPILER%" installer.iss

if %errorlevel% neq 0 (
    echo.
    echo ERROR: Inno Setup compilation failed. Check the output above.
    pause
    exit /b 1
)

echo.
echo ============================================================
echo   BUILD COMPLETE!
echo.
echo   Installer: installer_output\TallySyncManager_Setup_v1.0.0.exe
echo   EXE only:  dist\TallySyncManager\TallySyncManager.exe
echo ============================================================
echo.
pause
