@echo off
REM build.bat
REM =========
REM Run this from your project root to build TallySyncManager.exe
REM Double-click it or run it in your terminal.

echo.
echo ============================================
echo   TallySyncManager - EXE Builder
echo ============================================
echo.

REM Step 1: Install PyInstaller into the project
echo [1/4] Installing PyInstaller...
uv add pyinstaller --dev
if %errorlevel% neq 0 (
    echo ERROR: Failed to install PyInstaller
    pause
    exit /b 1
)

REM ─────────────────────────────────────────────────────────────────────────
REM Step 2: Write hooks\hook-cryptography.py
REM
REM WHY: cryptography >= 42 ships a Rust extension (_rust.pyd).
REM The default PyInstaller hook (_pyinstaller_hooks_contrib) spawns an
REM isolated subprocess to detect the OpenSSL version.  On machines with
REM AppLocker / WDAC Application Control policies that subprocess cannot
REM load the DLL and the build prints:
REM
REM   WARNING: Failed to collect submodules for
REM            'cryptography.hazmat.backends.openssl' ...
REM   ImportError: DLL load failed while importing _rust:
REM   An Application Control policy has blocked this file.
REM
REM FIX: drop a local hook into hooks\ — PyInstaller always prefers
REM hooks listed in hookspath=[] (our spec points to 'hooks') over the
REM installed contrib hooks.  Our replacement hook collects the package
REM with glob (never imports it, never touches the DLL policy).
REM ─────────────────────────────────────────────────────────────────────────
echo.
echo [2/4] Writing hooks\hook-cryptography.py (AppLocker workaround)...

if not exist hooks mkdir hooks

(
echo # hooks/hook-cryptography.py  -- AUTO-GENERATED by build.bat, do not edit by hand
echo # Overrides _pyinstaller_hooks_contrib hook to avoid AppLocker DLL block.
echo import glob, os
echo from PyInstaller.utils.hooks import collect_data_files
echo.
echo datas = collect_data_files^('cryptography'^)
echo.
echo def _find_binaries^(^):
echo     try:
echo         import importlib.util
echo         spec = importlib.util.find_spec^('cryptography'^)
echo         if spec is None or not spec.submodule_search_locations:
echo             return []
echo         pkg_dir = list^(spec.submodule_search_locations^)[0]
echo     except Exception:
echo         return []
echo     result = []
echo     for pattern in ^('*.pyd', '*.dll', '*.so'^):
echo         for src in glob.glob^(os.path.join^(pkg_dir, '**', pattern^), recursive=True^):
echo             parent = os.path.dirname^(pkg_dir^)
echo             dest   = os.path.relpath^(os.path.dirname^(src^), parent^)
echo             result.append^(^(src, dest^)^)
echo     return result
echo.
echo binaries = _find_binaries^(^)
echo.
echo hiddenimports = [
echo     'cryptography',
echo     'cryptography.fernet',
echo     'cryptography.hazmat',
echo     'cryptography.hazmat.primitives',
echo     'cryptography.hazmat.primitives.ciphers',
echo     'cryptography.hazmat.primitives.ciphers.algorithms',
echo     'cryptography.hazmat.primitives.ciphers.modes',
echo     'cryptography.hazmat.primitives.hashes',
echo     'cryptography.hazmat.primitives.hmac',
echo     'cryptography.hazmat.primitives.padding',
echo     'cryptography.hazmat.primitives.serialization',
echo     'cryptography.hazmat.primitives.asymmetric',
echo     'cryptography.hazmat.primitives.asymmetric.rsa',
echo     'cryptography.hazmat.backends',
echo     'cryptography.hazmat.backends.openssl',
echo     'cryptography.hazmat.bindings._rust',
echo     'cryptography.hazmat.bindings._rust.openssl',
echo     'cryptography.x509',
echo ]
) > hooks\hook-cryptography.py

if %errorlevel% neq 0 (
    echo ERROR: Failed to write hooks\hook-cryptography.py
    pause
    exit /b 1
)
echo    hooks\hook-cryptography.py written OK

REM Step 3: Clean previous build artifacts
echo.
echo [3/4] Cleaning old build files...
if exist build rmdir /s /q build
if exist dist  rmdir /s /q dist

REM Step 4: Build the EXE
echo.
echo [4/4] Building EXE - this takes 2-5 minutes...
uv run pyinstaller tally_app.spec

if %errorlevel% neq 0 (
    echo.
    echo ERROR: Build failed. Check the output above for errors.
    pause
    exit /b 1
)

echo.
echo ============================================
echo   BUILD SUCCESSFUL!
echo   EXE location: dist\TallySyncManager\TallySyncManager.exe
echo ============================================
echo.
pause
